/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/7.6.1/userguide/multi_project_builds.html
 */

// As of Gradle 7.6.1, when auto-provisioning is enabled,
// we must also specify the toolchain (we can't use the default any longer).
// https://github.com/gradle/foojay-toolchains
plugins {
    id("org.gradle.toolchains.foojay-resolver-convention") version "0.7.0"
}

rootProject.name = "javextras"
include("notnull-jetbrains")
