/*
 * This file was generated by the Gradle 'init' task.
 */
plugins {
    id("com.terheyden.javextras.java-library-publish-conventions")
}

description = "Provides a package-level annotation for marking nullability."
// See root build.gradle.kts for setting the verison.

dependencies {
    // Javax annotations (e.g. provided by SpotBugs) are not recommended past Java 9, see:
    // https://stackoverflow.com/questions/4963300/which-notnull-java-annotation-should-i-use
    // JetBrains, JSpecify, Lombok, or Checker Framework are better.
    // https://github.com/JetBrains/java-annotations
    // https://mvnrepository.com/artifact/org.jetbrains/annotations
    compileOnly("org.jetbrains:annotations:24.0.1")
}
