import gradle.kotlin.dsl.accessors._da021443478a11d115dea16225657459.implementation
import gradle.kotlin.dsl.accessors._da021443478a11d115dea16225657459.testImplementation

/*
 * This file was generated by the Gradle 'init' task.
 */
plugins {
    // Apply the common convention plugin for shared build configuration between library and application projects.
    id("com.terheyden.javextras.java-common-conventions")
    // Apply the java-library plugin for API and implementation separation.
    `java-library`
}

dependencies {
    // Libraries should pull in the API, but leave the implementation up to the caller:
    // https://mvnrepository.com/artifact/org.apache.logging.log4j/log4j-api
    implementation("org.apache.logging.log4j:log4j-api:2.20.0")
    testImplementation("org.apache.logging.log4j:log4j-core:2.20.0")
}
