/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    // Support convention plugins written in Kotlin. Convention plugins are build scripts in 'src/main' that automatically become available as plugins in the main build.
    `kotlin-dsl`
}

//dependencies {
//    // https://plugins.gradle.org/plugin/io.github.gradle-nexus.publish-plugin
//    implementation("io.github.gradle-nexus:publish-plugin:2.0.0-rc-1")
//}

repositories {
    // Use the plugin portal to apply community plugins in convention plugins.
    gradlePluginPortal()
}
